export type Item = {
    name: string
    catchCopy: string
    detail: string
    releaseDate: string
    img: string
    premium: boolean
};

const basePath = 'https://umaibou-api.herokuapp.com';
const list: Item[] = [
    {
        'name': 'とんかつソース味',
        'catchCopy': 'いちばん古いうまい棒！',
        'detail': '発売当初からある古参。もとは名前はソース味。とんかつソースだけに、カラシがピリリと効いてます。',
        'releaseDate': '1979年7月～',
        'img': `${basePath}/tonkatsu-sauce.png`,
        'premium': false,
    },
    {
        'name': 'サラミ味',
        'catchCopy': '味も香りもスパイスとスモーク！',
        'detail': 'スモークサラミスティックの昧を忠実に再現した昧。つまみに最適な大人のうまい棒',
        'releaseDate': '1979年～',
        'img': `${basePath}/salami.png`,
        'premium': false,
    },
    {
        'name': 'チーズ味',
        'catchCopy': '子どもから大人まで！定番のうまい棒！',
        'detail': 'スタンダードかつ飽きのこない不動の人気うまい棒。マイルドなチーズの香りが濃厚です。',
        'releaseDate': '1980年～',
        'img': `${basePath}/cheese.png`,
        'premium': false,
    },
    {
        'name': 'テリヤキバーガー味',
        'catchCopy': 'てりやきの独特の味が口いっぱいに！',
        'detail': 'ハンバーガーショップのおいしいテリヤキバーガーの味をうまい棒で再現。（発売当初はバーガー味）',
        'releaseDate': '1980年～',
        'img': `${basePath}/teriyaki-burger.png`,
        'premium': false,
    },
    {
        'name': 'やさいサラダ味',
        'catchCopy': '親しまれ続けている定番フレーバー！',
        'detail': 'やさいサラダ味のシーズニングを掛けた革新的なヘルシー志向のうまい棒。炭酸飲料との相性は抜群。',
        'releaseDate': '1980年～',
        'img': `${basePath}/yasai-salad.png`,
        'premium': false,
    },
    {
        'name': 'めんたい味',
        'catchCopy': 'ちょっと辛めのめんたい味！',
        'detail': '内袋についた濃い目のパウダ一をなめたくなる、辛めのめんたいをイメージを再現したうまい棒。',
        'releaseDate': '1982年～',
        'img': `${basePath}/mentai.png`,
        'premium': false,
    },
    {
        'name': 'たこ焼味',
        'catchCopy': '力リッと焼きあがった食感と香ばしさ！',
        'detail': '発売以来、親しまれているザクザク食感。甘辛ソースに青海苔、紅生姜まで入ってます。',
        'releaseDate': '1987年～',
        'img': `${basePath}/takoyaki.png`,
        'premium': false,
    },
    {
        'name': 'コーンポタージュ味',
        'catchCopy': '甘い香りでクリーミー！',
        'detail': '生地のコーンに良く合う、まろやかなコーンポタージュスープをそのままうまい棒で再現しました。',
        'releaseDate': '1992年～',
        'img': `${basePath}/corn-potage.png`,
        'premium': false,
    },
    {
        'name': 'エビマヨネーズ味',
        'catchCopy': 'マヨとエビの味がよ〜く分かる！',
        'detail': 'マヨネーズの濃厚な味わいと、ほのかにエビの風味が絶妙にマッチ。',
        'releaseDate': '2001年5月～',
        'img': `${basePath}/ebi-mayonnaise.png`,
        'premium': false,
    },
    {
        'name': '牛タン塩味',
        'catchCopy': 'レモンの風味と香ばしさ！',
        'detail': '牛タン塩が手軽に食べられる！おやつだけでなくおつまみにも最適です。',
        'releaseDate': '2007年5月～',
        'img': `${basePath}/gyutan-shio.png`,
        'premium': false,
    },
    {
        'name': 'なっとう味',
        'catchCopy': '茨城名物！本格ねばねば感！',
        'detail': '満を持して復活した伝説のうまい棒。納豆好きにはたまらない香りとネバネバをうまい棒で再現。',
        'releaseDate': '2012年12月～（1993年、1996年～1999年、2003年～2008年）',
        'img': `${basePath}/natto.png`,
        'premium': false,
    },
    {
        'name': 'シュガーラスク味',
        'catchCopy': 'ふんわり甘いラスクの食感',
        'detail': 'サクサク食感と甘すぎない上品な甘さがクセになります。食感のために小さな穴が4つあります。',
        'releaseDate': '2013年1月～',
        'img': `${basePath}/sugar-rusk.png`,
        'premium': false,
    },
    {
        'name': 'チョコレート',
        'catchCopy': 'サクッとうまいもう一本！',
        'detail': 'チョコレートをコーンパフにコーティングした、ちょっと違ううまい棒。※夏は販売していません。',
        'releaseDate': '1982年1月～',
        'img': `${basePath}/chocolate.png`,
        'premium': false,
    },
    {
        'name': 'やきとり味',
        'catchCopy': 'ジューシーな鶏とタレの美味しさ！',
        'detail': '炭火焼の焼鳥のタレの風味をそのままうまい棒に！香ばしさと濃厚な美味しさ広がります。',
        'releaseDate': '2015年1月～',
        'img': `${basePath}/yakitori.png`,
        'premium': false,
    },
    {
        'name': 'さとうきび味',
        'catchCopy': '南国ご当地うまい棒！',
        'detail': '沖縄県産のさとうきび使用のさとうきび味！沖縄エリアだけの限定です。お土産にどうぞ！',
        'releaseDate': '2018年6月～',
        'img': `${basePath}/satokibi.png`,
        'premium': false,
    },
    {
        'name': 'シナモンアップルパイ味',
        'catchCopy': 'シュガーラスクに続くスイーツ味!',
        'detail': 'りんごの爽やかな甘酸っぱさにシナモンの風味、パイのサクサク感をうまい棒で再現。東京エ リアだけの地域限定発売なので、お土産にもピッタリ!',
        'releaseDate': '2018年3月～',
        'img': `${basePath}/cinnamon-apple-pie.png`,
        'premium': false,
    },
    {
        'name': 'レモン味',
        'catchCopy': '暑い季節にスさわやかレモン味！',
        'detail': '爽やかなレモンの酸味とさっぱりとした甘さが口の中に広がる、暑い夏を吹き飛ばす商品です。',
        'releaseDate': '2019年6月〜',
        'img': `${basePath}/lemon.png`,
        'premium': false,
    },
    {
        'name': 'のり塩味',
        'catchCopy': 'ついにうまい棒から定番、のり塩味!',
        'detail': 'コーン生地にポテトを練り込み、ポテトチップスでおなじみの味をうまい棒で再現しました。のりの香ばしさとこだわりの塩がシンプルなのに奥深く、あと引くうまさとなっております。',
        'releaseDate': '2020年7月〜',
        'img': `${basePath}/nori-shio.png`,
        'premium': false,
    },
    {
        'name': 'プレミアム和風ステーキ味',
        'catchCopy': 'ツンと爽やかなわさび風味',
        'detail': '和と洋のわさびの風味を効かせた極上の和風ステーキ味のプレミアムうまい棒です。',
        'releaseDate': '2015年6月～',
        'img': `${basePath}/premium-wafu-steak.png`,
        'premium': true,
    },
    {
        'name': 'プレミアムモッツァレラチーズ&カマンベールチーズ味',
        'catchCopy': 'Wテイストリッチ＆クリーミー',
        'detail': '贅沢気分を味わえる、高級感溢れるうまい棒。モッツァレラとカマンベール、2種のチーズをたっぷり使用したワンランク上の味',
        'releaseDate': '2014年4月～',
        'img': `${basePath}/premium-mozzarella-cheese-and-camembert-cheese.png`,
        'premium': true,
    },
    {
        'name': 'プレミアム明太子味',
        'catchCopy': 'めんたい味とは違うリッチ&スパイシー',
        'detail': 'めんたいこパウダーを使用した本格的で、旨みと辛みの極上な味が楽しめるプレミアムなうまい棒',
        'releaseDate': '2014年4月～',
        'img': `${basePath}/premium-mentaiko.png`,
        'premium': true,
    },
    {
        'name': 'ドラゴンビスク味',
        'catchCopy': '『パズドラ×うまい棒』コラボ商品第2弾!!',
        'detail': 'パズドラ8周年を記念して、プレミアム仕様に仕上げました。この商品の為に特別に開発された「ドラゴンビスク味」です。',
        'releaseDate': '2020年6月〜',
        'img': `${basePath}/dragon-bisque.png`,
        'premium': true,
    }
];

export default list;